language: python
python:
- '3.5'
before_script:
- pip install pybuilder
script: pyb
branches:
  only:
  - master
before_deploy:
- pwd
- cd target/dist/janusgraph-python-0.0.1
- ls
deploy:
  provider: pypi
  user: debasishdebs
  server: https://test.pypi.org/legacy/
  password:
    secure: DVPXG7Ffe27PSn5chFjZKKu/lDQf+7OpGwJbRj7t5iFQ0vPQhqEEfC/mLU70rbrCZZgR2KjZTU3ZpO9kEOZfIfgZEn5azAd4Lt1C/kQRNn7jHQtH0H25lptlOgFqbDAeIAQGX8L5l7Z4eNlmpb4r+Yf1lBXsIVGMMZo8HqzV9gUu6jzEfGpcHK0VUaaSndbSs/uun19MMibynwtQ8B+zTX803PzCsYDvRN4Cz5LxKyswkfZ51086vL9l65odsfzPcOSbsrRpMHud7avGcEnWf4XQLLpgJ90LWwmX6mFFTUVXBqu2wcTJ2WiOeIv70YL7H6p9RgmMplIpJ/aXBOJmJsG9VOt6Mg4fTZRs02KG1SewcSDONQHysOt0PAWcOp/RQCVgYix+wvGd3xMAc/ia1DfbNhOscxoNXn+a0ymmt2VTc0tLEQIGgblhU5B1zcNrSScVUEP3ND5pU+Vl3uqnVPEPC1mmi/yI4ZeHqxP6WMv1akWUkIG9dmOryonMJIwyVgmX9/f4FXtUtOOAEJ4jIOGPL/WjUlAe54tZCRPGtAk2RRfeOI1KUGMOZJUWY0AYBE3K0XSenKAIYeFATCx2f8pxQQKqKJbDSpzAd16qYS0/9oENw+6Fe9ID2JcTu7Uw97qFbIKHyoRIWi2J50llMgyYS2MPFZbp7j0ZG/OyrXg=
  skip_cleanup: true
  on:
    branch: master
