language: python
python:
  - "3.5"
# command to install pybuilder
before_script:
  - pip install pybuilder
# Run pybuilder (pyb)
script: pyb
branches:
  only:
    - master

before_deploy:
  - cd target/dist/janusgraph-python-0.0.1
deploy:
  provider: pypi
  user: debasishdebs
  server: https://testpypi.python.org/pypi # Remove for deployment to official PyPi repo
  password: 2NInitu!!
  on:
    branch: master
