language: python
python:
  - "3.5"
# command to install pybuilder
before_script:
  - pip install pybuilder
# Run pybuilder (pyb)
script: pyb
branches:
  only:
    - master

before_deploy:
#  - cd ~/
#  - cd target/dist/janusgraph-python-0.0.1
  - pwd
  - cd target/dist/janusgraph-python-0.0.1
  - ls
deploy:
  provider: pypi
  user: debasishdebs
  server: https://test.pypi.org/ # Remove for deployment to official PyPi repo
  password: 2NInitu!!
  skip_cleanup: true
  on:
    branch: master
