language: python
python:
- '3.5'
before_script:
- pip install pybuilder
script: pyb
branches:
  only:
  - master
before_deploy:
- pwd
- cd target/dist/janusgraph-python-0.0.1
- ls
deploy:
  provider: pypi
  user: debasishdebs
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  on:
    branch: master
  password:
    secure: IbjUKptbV1AlZal0J6P1L1wJJ/40ooqnqGPB+kwN6pHlhua+/ZJP1bqXJJyqU9TjPL0slFwqbi/GbaynHz3yaSpc9GBHFAg+b4VzrP80+ivH7/Vq66Z9dLQ1xJkZwPITZ864J3r5/AjRm/F8CThOSV+RBz4nPW3LgJ+OcVIxGc78URmmH2XychVdZYr1hqg46hmUAxxbA7eq59qw3eQpYP65fXV22sT1QhoxIIE0OuiJeKf/lImwiGJ0OdvJo9ebemzbHE4gaxdQaMhZvVWeBQfZYYksVYAGDT5JLmQxYumd9OPckRrjJg8bB6ZBLXRD+0CArYCpzYUe0lgQx+t6/B9djbIRxD4jpsZHxYd7oUutpL56DCLau0kqtTsWzrholxsO9MgTqGk/9CL29wySX1OVyrpCTwmNSvG3i+3RUK7+PrQCorTNbsDDlpo0uGHxXhyOv1AQuFIEfjuCgWZYSG1TL4+l0dmAfJDoBXoQJP3ItqGO8iH011yUnWUTJYttVcT/EgpQc3DQihWU2RHKaVQR+M2wNu8dEP/8VlGBWQFNXM/BlwPj3dmF1TI8AnaFy1/8jNOkeWFeSI/80TFAayMUhBjgljvOr1T5wKyGx7+wcRraTj9/Kp4S6Az922/MnimoPYzcse5ScgsQfm3jdqnGvxn4ppcttBwKZoMDv24=
