language: python
python:
- '3.5'
before_script:
- pip install pybuilder
script: pyb
branches:
  only:
  - master
before_deploy:
- pwd
- cd target/dist/janusgraph-python-0.0.1
- ls
deploy:
  provider: pypi
  user: debasishdebs
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  on:
    all_branches: true
  password: Debasish1202