language: python
python:
- '3.5'
before_script:
- pip install pybuilder
script: pyb
branches:
  only:
  - master
before_deploy:
- pwd
- cd target/dist/janusgraph-python-0.0.1
- ls
deploy:
  provider: pypi
  user: debasishdebs
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  on:
    branch: master
  password:
    secure: GjmFR5zhh6Z98wnlaEW2I7Pzo7k+XvN+Pzv+WeVPtIK2EvhqjR2WIIiEQ4BzhlhZzQoZP9LjSl/jKw/jM7YoYCCI0RKUyoCewBWkNUznQ+rsfVS98taGWSq2Rq0xiMfEgA1zAU2cvBqNadJe0z/JlfIp28z6l9f9JyhHHhgynqvvUfdM9M1gumyJUAqLh81SJggAl00f6aMkRstpJQYXS/pUPtPQsNqmmxQR9tZm9Mz/9CZbvC2PuuSgn/HYE4uTznwSVD6HXs4hwqpjEs8WAREBv+lz684x4qpZCzjbS/Z6xFMb9EBVCg8/oJo6fpeSB3R8UDak1rXC6N9K5WnTNuCMZjgZmYgKQgoKbr6ox08V3RPW9OC6Djop08zlCXOVMnBBYcLkfmHVIoLoMo6VMnX1duwTHqCOpwvt8HK07nawW2CTJ1WZ2E/P+E/Liaai67mN+dwyNoygroO9VN4sffp/t/mPGaljaM1eov6Y9z6bdYSHyRmjKkxqcsAGn3ZbEudsCwablrbfq2lGJaVNX/K11+3DohsfQCUZNepfwQ8OB7Vf0r90djjITbYiwEfRrrw052QVxhyPdJ5JjJJHhzvbHQck1Wodyy38WjLCS8bTLMPNEPoGldYyzP/kLyymMvsvemQAA+wma4hjOXbRUeWWB7v68jCmPrV0caj0ikU=
