language: python
python:
- '3.5'
before_script:
- pip install pybuilder
script: pyb
branches:
  only:
  - master
before_deploy:
- pwd
- cd target/dist/janusgraph-python-0.0.1
- ls
deploy:
  provider: pypi
  user: debasishdebs
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  on:
    all_branches: true
  password:
    secure: FQnXpj8Id9e4tlgqT4rp/8br0ch+lEb9Gih82y+vQnfYQNoA3ynkcsTHpxc9ZH3RHo0UksoC49T1Kck8qrkHLw1prVvmm5h8CnSjo8zP6WWPoyOQ08nIM4ndd4wNfo6LfU+45PyNFs62JL6h3DmWhxJLlJaWn50cUAWHHSvpYlSsqU8CMK15mPlBRDS2Yjt0/TiXKA35wEcI3qaw7PdGiwVBCyKfqg4hwKxhzHXTm4jnsEhGbUEVN7yVjvk2qe40J9S2OJFjYVhaRAmX3UA7wqaGeI7qZk7+jRp2cQQcjIBFrN2jwbw7RgBWI/kZOUY2Bz7KRvFfikmUZhmTMGrp0MTxB/6RnfIzbSwzE+j6hIQbM95hcoJlz1sQnJxXjj2R94Cbt7lx5CfZyuBKYSfynPN1WbLD21/ZVy2yFKQNd9THvgVis/sE6dn5FbxHrE0tm4c/383c2bUCOirYmTbGoeRRCA8wYWKJp8v3AdUZOjXPpOSO/s8ZEM3qBs6y2m+uxa5mu8lBKRHMrCsLsprH9rzSZk3qqkdY3NSRrUgsAbAckzZfesluQIMt2v1LRTgaF7JXePXPjq6gQg9f+dHBA6saoc2DQCvREJlkyXVwlHLLz4ZNua69zAhwGfqjXXG7utYqyQLLuMJf1Rf5osQIv6WlHvZ7DCw2K5Daz6WTHOc=
env:
  global:
    PASSWORD: GjmFR5zhh6Z98wnlaEW2I7Pzo7k+XvN+Pzv+WeVPtIK2EvhqjR2WIIiEQ4BzhlhZzQoZP9LjSl/jKw/jM7YoYCCI0RKUyoCewBWkNUznQ+rsfVS98taGWSq2Rq0xiMfEgA1zAU2cvBqNadJe0z/JlfIp28z6l9f9JyhHHhgynqvvUfdM9M1gumyJUAqLh81SJggAl00f6aMkRstpJQYXS/pUPtPQsNqmmxQR9tZm9Mz/9CZbvC2PuuSgn/HYE4uTznwSVD6HXs4hwqpjEs8WAREBv+lz684x4qpZCzjbS/Z6xFMb9EBVCg8/oJo6fpeSB3R8UDak1rXC6N9K5WnTNuCMZjgZmYgKQgoKbr6ox08V3RPW9OC6Djop08zlCXOVMnBBYcLkfmHVIoLoMo6VMnX1duwTHqCOpwvt8HK07nawW2CTJ1WZ2E/P+E/Liaai67mN+dwyNoygroO9VN4sffp/t/mPGaljaM1eov6Y9z6bdYSHyRmjKkxqcsAGn3ZbEudsCwablrbfq2lGJaVNX/K11+3DohsfQCUZNepfwQ8OB7Vf0r90djjITbYiwEfRrrw052QVxhyPdJ5JjJJHhzvbHQck1Wodyy38WjLCS8bTLMPNEPoGldYyzP/kLyymMvsvemQAA+wma4hjOXbRUeWWB7v68jCmPrV0caj0ikU=
