#!/usr/bin/env python


from gremlin_python.process.graph_traversal import __
from janusgraph_python.core.attribute.TextPredicate.Text import Text
from janusgraph_python.core.datatypes.Point import Point
from janusgraph_python.core.datatypes.Circle import Circle
from janusgraph_python.core.attribute.GeoPredicate.Geo import Geo
from janusgraph_python.driver.ClientBuilder import JanusGraphClient


import pprint


if __name__ == '__main__':

    g = JanusGraphClient().build(url="10.153.22.172", port="8182", graph="gg").get_traversal()

    # Next up would be adding a property with GeoShape data type back to JanusGraph
    # Add a new node of type monster named Stymphalian birds.

    countBull = g.V().has("name", "Stymphalian birds").count().next()
    if countBull >= 1:
        birds = g.V().has("name", "Stymphalian birds").next()
    else:
        birds = g.addV("monster").property("name", "Stymphalian birds").next()

    # Retrive hercules node, so that we can add a new edge to it.
    hercules = g.V().has("name", Text.textContainsFuzzy("herculeas")).next()
    # Now we add edge b/w the vertices created and retrieved.
    # Since we are going to add a GeoShape point specifying where the battle happened,
    # First let us create the GeoShape obj

    # We define arcadia point by its lat and long
    arcadia = Circle(37.35, 22.15, 5)
    # We add arcadia POINT to our newly created edge.
    edgeAdded = g.V(birds).as_("to").V(hercules).addE("battled").property("time", 6).property("place", arcadia).to("to").next()
    print(15*"=")
    print(edgeAdded)
    print("Was edge added")
    print(15 * "=")

    print(15 * "=")
    print("Testing retrival of GeoShapes")
    edgesH = g.V().has("name", Text.textContainsFuzzy("herculeas")).outE("battled").valueMap("place").toList()
    print(edgesH)
    print(15 * "=")

    # print(15 * "=")
    # print("Testing another query (herculeasBattles)")
    # herculeasBattles = g.V().has("name", Text.textContainsPrefix("hercu")).\
    #                         outE("battled").project("time", "place").by("time").by("place").toList()
    # print(herculeasBattles)
    # print(15 * "=")

    print(15 * "=")
    print("Testing edge serialization")
    id = g.E().id().next()
    print(id)
    print(15 * "=")

    # Next I'm going to test GeoPredicates
    # shape = Circle(23, 37, 1000)
    print(15 * "=")
    shape = Circle(23, 37, 1000)
    edges = g.V().has("name", Text.textContainsFuzzy("herculeas")).\
                            outE().has("place", Geo.geoWithin(shape)).toList()
    herculesBattledWith = g.V().has("name", Text.textContainsFuzzy("herculeas")).\
                            outE().has("place", Geo.geoWithin(shape)).inV().path().by(__.valueMap(True)).toList()
    print("Edges etrived using Geo Predicates")
    pprint.pprint(herculesBattledWith)
    print(15 * "=")
    pprint.pprint(edges)
    print(15 * "=")
